### ISSUE TITLE
Job Processing with source file / project name in its title

### ISSUE THREAD

**Issue by Dendraspis** [staxrip/staxrip#162]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have a few new projects started and ffmsindex is running. Most the time it's hard to say if I dragged a file already to StaxRip or not. The only solution at the moment is:  waiting till every file is indexed or open each log and check the path.

**Describe the solution you'd like**
Project name is set:  write its name on the title,
Ex. _**StaxRip - Job Processing [Holiday 2018]**_
Project name is unset, e.g. in case of indexing:
Ex. _**StaxRip - Job Processing [People_Are_Awesome_1080p.mp4]**_

**Describe alternatives you've considered**
Of course the name or another identifier could be placed somewhere else.

**Explain why the feature matters to you**
While encoding it's not that important, because you have the output with the paths, but it would be faster to see, especially when using parallel encodes, so that you can't refer by the job list to the current/opened job.

**Additional context**
. / .

**Comment by JonathonSunshine** [comment]
please make this optional....

**Comment by stax76** [comment]
This is potentially difficult to build like many requests, processes like ffmsindex that don't write output except maybe progress caused staxrip not writing the command line before processing to the processing log, this is fixed in the next build so while processing (indexing) the command line is visible so the source file name can be seen, I hope that's good enough.

PS: your other request you closed is available in the next build, the processing dialog has a new menu and some layout improvements.

**Comment by Dendraspis** [comment]
This sounds wonderful.  When available I'll try it out.  🙂 

PS: Saw it already on the changelog.  😉  Still can't believe it, I'm absolutely curious.  😲

**Comment by Dendraspis** [comment]
Checked, verified, happy!  😄 

Thanks for including the command line.  👍
