### ISSUE TITLE
Video Track Language does not work

### ISSUE THREAD

**Issue by THGhost** [staxrip/staxrip#1649]
**Describe the bug**
Selecting any language tag in "Container Options > Options > Video Track Language" does not carry the selected language tag over to the final encode, at least according to MKVToolNix GUI.

**Expected behavior**
Whichever language tag is selected should be embedded into the final encode's video track.

**How to reproduce the issue**

https://i.imgur.com/KpLjXlu.png
Input any video file, go to "Container Options > Options > Video Track Language", select any language tag, click "OK".

Start & finish the encode, input the new video file into MKVToolNix GUI and see that the video track does not have the selected language tag in place.

https://i.imgur.com/8OaQF7K.png
Here is a final encode inside MKVToolNix GUI. Notice how the video track does not have the "en-GB" tag. It is also set to default, which (to me) is unnecessary. Could a "Default" toggle be added to the "Container Options > Options" window as well please? Or just make it so that the video track is never set to default instead?

StaxRip version: 2.46.4, but this bug has existed for a while.

**Comment by Dendraspis** [comment]
Indeed, a pretty sneaky bug. But I have fixed it now for the next release.

> StaxRip version: 2.46.4, but this bug has existed for a while.

I wished you have written this report yesterday, so it could have been already fixed in `v2.46.4`. 

> It is also set to default, which (to me) is unnecessary. Could a "Default" toggle be added to the "Container Options > Options" window as well please? Or just make it so that the video track is never set to default instead?

This is optional and disabled by default:

<img width=600 src=https://github.com/user-attachments/assets/f37fe257-1d73-4d78-871b-3878374cf9ac>

**Comment by Dendraspis** [comment]
It would be nice if you could verify, that it works with `v2.46.5` and give me a short feedback on that.

**Comment by THGhost** [comment]
The Video Track Language option appears to carry over to the final encode now 👍Although the Default option still persists even with the Take over Language option enabled.

**Comment by Dendraspis** [comment]
Ah, totally missed that point.
Nowadays it is sort of unnecessary, but what's the point of not having it set as *default track*? Does it really bother you that much?

**Comment by THGhost** [comment]
It's more of an OCD thing. Just wanting everything to be perfect. Although I see no need for the video track to be set to Default when there's only ever 1 video track anyway. It would only make sense to make an audio or subtitle track the default track when there are other tracks available, agreed? 🤷‍♀️

**Comment by Dendraspis** [comment]
Not really.  🤔 

The `default` flag is set by `mkvmerge` automatically. Your thinking of *"we only need the default track if there are multiple tracks"* is a bit misleading, it's more like *"no matter how many tracks there are, play the default track of each type"*. 
Back in time there were issues with some (hardware) players because of that.
