### ISSUE TITLE
Staxrip will try to append CHUNKS even if chunks = 1

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#438]
**BUG:**
When there are files called file_chunk2.hevc  and file_chunk3.hevc (...) in the temp folder, Staxrip will attempt to append them when muxing, even if chunk encoding is not activated (i.e chunks =1).
These files could happen to be there due to a previous encoding.

**Expected behaviour**
If chunks = 1 then those files should be ignored, and muxing should not append them.
Muxing should work SMARTLY.
If chunks = 1 , look for file_out.hevc, ignore any other
If chunks = 2 look for file_out.hevc and file_chunk2.hevc, ignore any other
If chunks = 3 look for file_out.hevc and file_chunk2.hevc and file_chunk3.hevc, ignore any other

Here is the complete log for your pleasure: it shows that NO second chunk has been encoded, but muxer has appended a chunk from a previous processing.
```

------------------------- System Environment -------------------------

StaxRip    : 2.1.7.1
Windows    : Windows 10 Home 2004
Language   : English (United States)
CPU        : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
GPU        : Intel(R) HD Graphics 530, NVIDIA GeForce GTX 960M
Resolution : 1920 x 1080
DPI        : 96

----------------------- Media Info Source File -----------------------

D:\Downloads\_IDM Downloads\Timecode sample - 25fps.mp4

General
Complete name            : D:\Downloads\_IDM Downloads\Timecode sample - 25fps.mp4
Format                   : MPEG-4
Format profile           : Base Media / Version 2
Codec ID                 : mp42 (isom/mp42)
File size                : 4.88 MiB
Duration                 : 1 min 18 s
Overall bit rate mode    : Variable
Overall bit rate         : 522 kb/s
Encoded date             : UTC 2017-12-17 15:18:14
Tagged date              : UTC 2017-12-17 15:18:14
gsst                     : 0
gstd                     : 78460

Video
ID                       : 1
Format                   : AVC
Format/Info              : Advanced Video Codec
Format profile           : High@L3.1
Format settings          : CABAC / 1 Ref Frames
Format, CABAC            : Yes
Format, Reference frames : 1 frame
Format, GOP              : M=1, N=60
Codec ID                 : avc1
Codec ID/Info            : Advanced Video Coding
Duration                 : 1 min 18 s
Bit rate                 : 327 kb/s
Maximum bit rate         : 471 kb/s
Width                    : 1 280 pixels
Height                   : 720 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Constant
Frame rate               : 25.000 FPS
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 8 bits
Scan type                : Progressive
Bits/(Pixel*Frame)       : 0.014
Stream size              : 3.06 MiB (63%)
Tagged date              : UTC 2017-12-17 15:18:15
Color range              : Limited
Color primaries          : BT.709
Transfer characteristics : BT.709
Matrix coefficients      : BT.709
Codec configuration box  : avcC

Audio
ID                       : 2
Format                   : AAC LC
Format/Info              : Advanced Audio Codec Low Complexity
Codec ID                 : mp4a-40-2
Duration                 : 1 min 18 s
Bit rate mode            : Variable
Bit rate                 : 192 kb/s
Maximum bit rate         : 201 kb/s
Channel(s)               : 2 channels
Channel layout           : L R
Sampling rate            : 44.1 kHz
Frame rate               : 43.066 FPS (1024 SPF)
Compression mode         : Lossy
Stream size              : 1.79 MiB (37%)
Title                    : IsoMedia File Produced by Google, 5-11-2011
Encoded date             : UTC 2017-12-17 15:18:15
Tagged date              : UTC 2017-12-17 15:18:15

----------------------------- Demux audio -----------------------------

MP4Box 1.1.0-DEV-rev390-g4228658a9-x64-gcc10.2.0 Patman86

"C:\Program Files\StaxRip\Apps\Support\MP4Box\MP4Box.exe" -single 2 -out "C:\Temp\_StaxRip\Timecode sample - 25fps_temp\ID1 {IsoMedia File Produced by Google, 5-11-2011}.m4a" "D:\Downloads\_IDM Downloads\Timecode sample - 25fps.mp4"

Start:    11:12:51
End:      11:12:51
Duration: 00:00:00

General
Complete name         : C:\Temp\_StaxRip\Timecode sample - 25fps_temp\ID1 {IsoMedia File Produced by Google, 5-11-2011}.m4a
Format                : MPEG-4
Format profile        : Base Media
Codec ID              : isom (isom)
File size             : 1.81 MiB
Duration              : 1 min 18 s
Overall bit rate mode : Variable
Overall bit rate      : 194 kb/s
Encoded date          : UTC 2021-01-11 09:12:51
Tagged date           : UTC 2021-01-11 09:12:51

Audio
ID                    : 2
Format                : AAC LC
Format/Info           : Advanced Audio Codec Low Complexity
Format profile        : AAC@L2
Codec ID              : mp4a-40-2
Duration              : 1 min 18 s
Bit rate mode         : Variable
Bit rate              : 192 kb/s
Nominal bit rate      : 728 b/s
Maximum bit rate      : 201 kb/s
Channel(s)            : 2 channels
Channel layout        : L R
Sampling rate         : 44.1 kHz
Frame rate            : 43.066 FPS (1024 SPF)
Compression mode      : Lossy
Stream size           : 1.79 MiB (99%)
Encoded date          : UTC 2021-01-11 09:12:51
Tagged date           : UTC 2021-01-11 09:12:51

---------------------- Indexing using ffmsindex ----------------------

"C:\Program Files\StaxRip\Apps\Plugins\Dual\ffms2\ffmsindex.exe" "D:\Downloads\_IDM Downloads\Timecode sample - 25fps.mp4" "C:\Temp\_StaxRip\Timecode sample - 25fps_temp\temp.ffindex"

Writing index... done.

Start:    11:12:52
End:      11:12:52
Duration: 00:00:00

---------------------------- Configuration ----------------------------

Template                : ZK x265 480p BT709 Base
Video Encoder Profile   : x265
Container/Muxer Profile : MKV (mkvmerge)

--------------------------- AviSynth Script ---------------------------

AddAutoloadDir("C:\Program Files\StaxRip\Apps\FrameServer\AviSynth\plugins")
AddAutoloadDir("C:\Program Files\Staxrip\Settings\Plugins\AviSynth")
AddAutoloadDir("C:\Program Files\Staxrip\Settings\Plugins\Dual")
LoadPlugin("C:\Program Files\StaxRip\Apps\Plugins\Dual\ffms2\ffms2.dll")
LoadPlugin("C:\Program Files\StaxRip\Apps\Plugins\AVS\JPSDR\Plugins_JPSDR.dll")
FFVideoSource("D:\Downloads\_IDM Downloads\Timecode sample - 25fps.mp4", cachefile="C:\Temp\_StaxRip\Timecode sample - 25fps_temp\temp.ffindex")
#AssumeFPS(25)
LanczosResizeMT(856, 480, prefetch=4)
Trim(100, 145) + Trim(1375, 1420)

------------------------- Source Script Info -------------------------

Width     : 1280
Height    : 720
Frames    : 1960
Time      : 01:18.400
Framerate : 25 (25/1)
Format    : YUV420P8

------------------------- Target Script Info -------------------------

Width     : 856
Height    : 480
Frames    : 92
Time      : 00:03.680
Framerate : 25 (25/1)
Format    : YUV420P8

--------------------------- Video encoding ---------------------------

x265 M-3.4+35-772bb4c84-x64-gcc10.2.0 Patman86

"C:\Program Files\StaxRip\Apps\Encoders\x265\x265.exe" --crf 24 --preset slow --output-depth 10 --output "C:\Temp\_StaxRip\Timecode sample - 25fps_temp\Timecode sample - 25fps_out.hevc" "C:\Temp\_StaxRip\Timecode sample - 25fps_temp\Timecode sample - 25fps.avs"

avs+ [info]: AviSynth+ 3.6.2 (r3341, master, x86_64)
avs+ [info]: Video colorspace: YUV420 (YV12)
avs+ [info]: Video depth: 8
avs+ [info]: Video resolution: 856x480
avs+ [info]: Video framerate: 25/1
avs+ [info]: Video framecount: 92
avs+ [info]: 856x480 fps 25/1 i420p8 frames 0 - 91 of 92
raw  [info]: output file: C:\Temp\_StaxRip\Timecode sample - 25fps_temp\Timecode sample - 25fps_out.hevc
x265 [info]: HEVC encoder version x265M 3.4+35-772bb4c84
x265 [info]: build info [Windows][MSVC 1928][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main 10 profile, Level-3 (Main tier)
x265 [info]: Thread pool created using 8 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 3 / wpp(8 rows)
x265 [warning]: Source height < 720p; disabling lookahead-slices
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : star / 57 / 3 / 3
x265 [info]: Keyframe min / max / scenecut / bias  : 25 / 250 / 40 / 5.00 
x265 [info]: Lookahead / bframes / badapt        : 25 / 4 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 4 / on / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 2 / 1.0 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-24.0 / 0.60
x265 [info]: tools: rect limit-modes rd=4 psy-rd=2.00 rdoq=2 psy-rdoq=1.00
x265 [info]: tools: rskip mode=1 signhide tmvp strong-intra-smoothing deblock
x265 [info]: tools: sao
x265 [info]: frame I:      1, Avg QP:22.44  kb/s: 1123.60 
x265 [info]: frame P:     20, Avg QP:27.63  kb/s: 119.84  
x265 [info]: frame B:     71, Avg QP:31.24  kb/s: 58.88   
x265 [info]: Weighted P-Frames: Y:0.0% UV:0.0%
x265 [info]: consecutive B-frames: 9.5% 4.8% 4.8% 0.0% 81.0% 
encoded 92 frames in 1.98s (46.46 fps), 83.71 kb/s, Avg QP:30.36

Start:    23:13:42
End:      23:13:45
Duration: 00:00:02

General
Complete name        : C:\Temp\_StaxRip\Timecode sample - 25fps_temp\Timecode sample - 25fps_out.hevc
Format               : HEVC
Format/Info          : High Efficiency Video Coding
File size            : 40.3 KiB
Duration             : 640 ms
Overall bit rate     : 516 kb/s
Writing library      : x265M - 3.4+35-772bb4c84:[Windows][MSVC 1928][64 bit] 10bit

Video
Format               : HEVC
Format/Info          : High Efficiency Video Coding
Format profile       : Main 10@L3@Main
Duration             : 640 ms
Width                : 856 pixels
Height               : 480 pixels
Display aspect ratio : 16:9
Frame rate           : 25.000 FPS
Color space          : YUV
Chroma subsampling   : 4:2:0
Bit depth            : 10 bits
Writing library      : x265M - 3.4+35-772bb4c84:[Windows][MSVC 1928][64 bit] 10bit

---------------------------- Muxing to MKV ----------------------------

mkvmerge 52

"C:\Program Files\StaxRip\Apps\Support\MKVToolNix\mkvmerge.exe" -o "R:\Timecode sample - 25fps.mkv" "C:\Temp\_StaxRip\Timecode sample - 25fps_temp\Timecode sample - 25fps_out.hevc" + "C:\Temp\_StaxRip\Timecode sample - 25fps_temp\Timecode sample - 25fps_out_chunk2.hevc" --ui-language en --title ""

mkvmerge v52.0.0 ('Secret For The Mad') 64-bit
'C:\Temp\_StaxRip\Timecode sample - 25fps_temp\Timecode sample - 25fps_out.hevc': Using the demultiplexer for the format 'HEVC/H.265'.
'C:\Temp\_StaxRip\Timecode sample - 25fps_temp\Timecode sample - 25fps_out_chunk2.hevc': Using the demultiplexer for the format 'HEVC/H.265'.
'C:\Temp\_StaxRip\Timecode sample - 25fps_temp\Timecode sample - 25fps_out.hevc' track 0: Using the output module for the format 'HEVC/H.265 (unframed)'.
'C:\Temp\_StaxRip\Timecode sample - 25fps_temp\Timecode sample - 25fps_out_chunk2.hevc' track 0: Using the output module for the format 'HEVC/H.265 (unframed)'.
No append mapping was given for the file no. 1 ('C:\Temp\_StaxRip\Timecode sample - 25fps_temp\Timecode sample - 25fps_out_chunk2.hevc'). A default mapping of 1:0:0:0 will be used instead. Please keep that in mind if mkvmerge aborts with an error message regarding invalid '--append-to' options.
The file 'R:\Timecode sample - 25fps.mkv' has been opened for writing.
Appending track 0 from file no. 1 ('C:\Temp\_StaxRip\Timecode sample - 25fps_temp\Timecode sample - 25fps_out_chunk2.hevc') to track 0 from file no. 0 ('C:\Temp\_StaxRip\Timecode sample - 25fps_temp\Timecode sample - 25fps_out.hevc').
The cue entries (the index) are being written...
Multiplexing took 0 seconds.

Start:    23:13:45
End:      23:13:45
Duration: 00:00:00

General
Complete name        : R:\Timecode sample - 25fps.mkv
Format               : Matroska
Format version       : Version 4
File size            : 73.1 KiB
Duration             : 5 s 520 ms
Overall bit rate     : 108 kb/s
Encoded date         : UTC 2021-01-11 21:13:45
Writing application  : mkvmerge v52.0.0 ('Secret For The Mad') 64-bit
Writing library      : libebml v1.4.1 + libmatroska v1.6.2

Video
ID                   : 1
Format               : HEVC
Format/Info          : High Efficiency Video Coding
Format profile       : Main 10@L3@Main
Codec ID             : V_MPEGH/ISO/HEVC
Duration             : 5 s 520 ms
Bit rate             : 95.0 kb/s
Width                : 856 pixels
Height               : 480 pixels
Display aspect ratio : 16:9
Frame rate mode      : Constant
Frame rate           : 25.000 FPS
Color space          : YUV
Chroma subsampling   : 4:2:0
Bit depth            : 10 bits
Bits/(Pixel*Frame)   : 0.009
Stream size          : 64.0 KiB (88%)
Writing library      : x265M - 3.4+35-772bb4c84:[Windows][MSVC 1928][64 bit] 10bit
Default              : Yes
Forced               : No

---------------------------- Job Complete ----------------------------

Start:    23:13:42
End:      23:13:45
Duration: 00:00:03


```

**Comment by JJKylee** [comment]
Which is **garbage collection**... 😆
Sorry about my lame joke. 😄

**Comment by Dendraspis** [comment]
@JJKylee 
I agree, if those chunk files are deleted afterwards.  😂 

@44vince44 
Do you also tested this with 3-pass mode, if the same issue occurs?
Sorry for more lame jokes. 😆 

Fixed with the next beta - you know how it works.  😁

**Comment by Patman86** [comment]
I think it's not fixed. I encoded a video file with 4 chunks and then encoded the same video with 2 chunks. Result: All chunks are merged.

**Comment by Dendraspis** [comment]
@Patman86 
You do it on purpose to annoy me, don't you? 😕

But you're right, the fix only works if you change chunks to 1. 🙄
Seems like I need a break after the fix...

**Comment by Patman86** [comment]
I have to duel a little with vince 😆🤣

**Comment by Dendraspis** [comment]
@Patman86 
A duel on my shoulders - very nice!  😝 

Ok, should be fixed now - I mean ***really***!

But now I hesitate to close this issue again.  🤣   Please do your testing first...

**Comment by Patman86** [comment]
Is fixed!!!

**Comment by Dendraspis** [comment]
@Patman86 
Are you sure? Or are you going to report the next mistake right after I closed the issue again?!   😆 
Maybe I should wait 1 ... or 2 .... months. 🤔

**Comment by Patman86** [comment]
I'm sure. I tested different scenarios.

**Comment by 44vince44** [comment]
@Patman86 what are you testing ? did @stax76 release a hotfix ?

**Comment by Patman86** [comment]
> @Patman86 what are you testing ? did @stax76 release a hotfix ?

You found the file #480

**Comment by 44vince44** [comment]
Yes I did! Thank you @Patman86 ! I will do all the testing in the morning !

**Comment by Dendraspis** [comment]
@44vince44 
Take the exe from [here](https://github.com/staxrip/staxrip/issues/430#issuecomment-759125039) so you can everything at once. 😁 
Have fun ...

**Comment by 44vince44** [comment]
@Patman86 @Dendraspis I confirm, this is working!
