### ISSUE TITLE
Bug Demux H265

### ISSUE THREAD

**Issue by papa-pitufo** [staxrip/staxrip#632]
When eac3to try to Demux a 4k file, in the window (upper right) select "none" when must select H265 by defect.  If you don't change none to H265, the StaxRip crash.

**Comment by stax76** [comment]
You skipped the issue template and wrote only two short sentences...

bd or .m2ts?

**Comment by stax76** [comment]
I'll take a look.

**Comment by 44vince44** [comment]
maybe this is the .ts/.m2ts issue.

What is your file ? can you drop here the error report ?
- if your file is .m2ts, can you change extension to .ts and see if it works ?

**Comment by stax76** [comment]
@papa-pitufo 

I don't have a compatible sample file, I have a h264 m2ts file but with that it's not crashing.

When staxrip crashes it's showing a dialog that was particularly designed for crashes, it has a Copy Message feature at the bottom, please copy the message or make a screenshot.

**Comment by 44vince44** [comment]
@stax76 if his file is indeed m2ts, then it is a known issue: eac3to will not handle it correctly. by ranaming to .ts, the handler will be ffmpeg, and it should work.
I'm waiting that he answers...

**Comment by stax76** [comment]
papa-pitufo said it's a file, .m2ts is the only file type registered for eac3to, so it must be .m2ts.

Your wiki page should help papa-pitufo:

https://github.com/staxrip/staxrip/wiki/How-to-handle-.ts-and-.m2ts-files-in-StaxRip

**Comment by 44vince44** [comment]
So this is the known problem of .m2ts
@stax76 if you want to have such a file, you can download the chameleon.m2ts that we have already used previously.
Here's the link: https://thedigitaltheater.com/dolby-trailers/
chose the file :chameleon.

**Comment by stax76** [comment]
@44vince44 

We can try changing the defaults so .m2ts is remuxed to mkv using ffmpeg.

@papa-pitufo 

How was your .m2ts file created?

**Comment by 44vince44** [comment]
@stax76 I think it's would be a good idea,  since eac3to is not being developed and updated any longer...

**Comment by JJKylee** [comment]
> We can try changing the defaults so .m2ts is remuxed to mkv using ffmpeg.

I'm kind'a neutral on this matter. Maybe @Dendraspis will regret eac3to is gradually losing its place in StaxRip. 😁

In the meantime, you can try this, @papa-pitufo:

![StaxRip_2 2 0_ffmpeg_as_ts-m2ts_preprocessor_20210327](https://user-images.githubusercontent.com/3157518/112728683-af061b00-8ee5-11eb-942e-317ff600b580.jpg)

`Tools` > `Settings` > `Preprocessing`

**Comment by Dendraspis** [comment]
@JJKylee 
I you eac3to outside of StaxRip, so there is no problem for me. But thanks thinking of me.  😁 
I just don't care about "bug reports" like this. Reminds me of *"My printer doesn't print, what's wrong?"*  🙄 

Btw:   eac3to has no problems demuxing h265 streams out of mkv or m2ts files.

**Comment by 44vince44** [comment]
@Dendraspis can you try the chameleon file ?

**Comment by JJKylee** [comment]
Off topic:

In trying to modify the preprocessor, I've found that the letter `& `(`&` and space) in the title field becomes `_`(underscore) (in 2.2.0).

For example `DGIndex: Demux & Index MPEG-2` becomes `DGIndex: Demux _Index MPEG-2`. 🙄

**Comment by JJKylee** [comment]
> @Dendraspis can you try the chameleon file ?

![StaxRip_2 2 0_hotfix_eac3to_as_m2ts_preprocessor_fails_on_chameleon_20210327](https://user-images.githubusercontent.com/3157518/112729814-65203380-8eeb-11eb-871c-6f4a22206ea4.jpg)

To save his precious time, I did it for him. 😝

**Comment by Dendraspis** [comment]
@JJKylee 
Disable all audio tracks and it will work.  😉

**Comment by 44vince44** [comment]
@Dendraspis well it won't be very useful if we disable all audio tracks (is that another joke ???)

OR demux it with ffmpeg ! (by simply renaming it to *.ts) it should work !

**Comment by 44vince44** [comment]
@Dendraspis I think you weren't following up this matter, because you were very busy on something else. here is some info:

- Staxrip CAN process a m2ts file without pre-remuxing to mkv (pre-processing). So asking Eac3to to disable audio tracks is not useful.
- It seems that ffmpeg can handle very well the m2ts. But ffmpeg had problems with .ts files, and that was BEFORE @JJKylee gave the proper syntax for ffmpeg (if I'm correct...)

SO we should maybe consider handling all the pre-processing "re-mux to mkv" to ffmpeg, i.e: treat .m2ts as .ts is currently treated.

**Comment by JJKylee** [comment]
Per @Dendraspis's recommendation, I tried various audio disabling options, and I've reached this conclusion:
`eac3to` fails to decode _only_ the second audio track in `chameleon`. But it happens to be an `E-AC-3 with JOC`(eac3 Atmos) audio.

So `eac3to` fails to decode an `eac3` audio only. Hahaha... 😅🤣

> * It seems that ffmpeg can handle very well the m2ts. But ffmpeg had problems with .ts files, and that was BEFORE @JJKylee gave the proper syntax for ffmpeg (if I'm correct...)

I guess so too.

**Comment by papa-pitufo** [comment]
Sorry, I'm out of home.

When you select folder or file 4k, it's the same, it show a window where eac3to goes to Demux.  It's show audio and subtitles.

In upper left it has a window where eac3to select the codec, well shows "Nothing" .  And if you don't touch anything and push run, staxrip crash.
You must change to H265 in order to demux right.  In other version you din't need anything.

I would like explain better but english it not my mother tonge and I'm not sure if anyone understand me.

Best regards

**Comment by papa-pitufo** [comment]
> @papa-pitufo
> 
> I don't have a compatible sample file, I have a h264 m2ts file but with that it's not crashing.
> 
> When staxrip crashes it's showing a dialog that was designed for crashes, it has a Copy Message feature at the bottom, please copy the message or make a screenshot.

Sorry, not crash StaxRip, crash demux.  Sorry again

**Comment by stax76** [comment]
The ampersand issue is fixed.

**Comment by papa-pitufo** [comment]
> The ampersand issue is fixed.

Thank you very much

**Comment by 44vince44** [comment]
@papa-pitufo your problem is not fixed.

If you want to demux without crash, rename:

Myvideo.m2ts -> Myvideo.ts

**Comment by Dendraspis** [comment]
What I've done now is:

- Add *m2ts*  to ffmpeg-remux
- Rename *ffmpeg: Re-mux TS to MKV* to ***ffmpeg: Re-mux (M2)TS to MKV***
- Disable eac3to per default
- Move eac3to to the top

So *eac3to* is disabled, but with a simple click it can be used to demux m2ts files again.

*eac3to* is a nice tool, but it has some known bugs, that probably never will be fixed. So using the re-mux step seems to be better than wrestling with such bugs. Experienced users can enable is if needed/wanted/necessary/bla/bla/bla.

**Comment by JJKylee** [comment]
> So _eac3to_ is disabled, but with a simple click it can be used to demux m2ts files again.
> 
> _eac3to_ is a nice tool, but it has some known bugs, that probably never will be fixed. So using the re-mux step seems to be better than wrestling with such bugs. Experienced users can enable is if needed/wanted/necessary/bla/bla/bla.

The first thing I do with a fresh install is deleting `eac3to` as a preprocessor, and `Ingest HDR` from the menu. 😝

**Comment by 44vince44** [comment]
@JJKylee I have something for you:
Please download this demo (500 MB approx)
https://4kmedia.org/lg-oled-art-uhd-4k-demo/

This has a ts file with hevc stream.

FFMPEG won't be able to demux it, but EAC3TO will.... You can check, just drop it on a standard staxrip v2.2 and see how it crashes...

**Comment by JJKylee** [comment]
You're right, @44vince44.

FFmpeg fails no matter what (to the best of my knowledge) while eac3to succeeds.
Quite naturally, demuxing via FFmpeg (`Tools` > `Advanced` > `Demux`) also fails.
I can't figure out what the cause is. Maybe it's an FFmpeg bug or something. 🤔

At last, there's one more reason we need to keep eac3to alive. 😁

**Comment by 44vince44** [comment]
@JJKylee @Dendraspis this is the solution I'm proposing, which seems to handle all possible formats known to me, it requires 3 pre-processing handlers instead of the two current ones involving ts, m2ts:

- ffmpeg remux (ts with avc -> mkv)
- ffmpeg remux (m2ts with avc or hevc -> mkv)
- eac3to demux (ts with hevc)

**Comment by JJKylee** [comment]
What if we let ffmpeg take care of `m2ts` and eac3to, `ts` as a whole?
Is there any problem with eac3to in demuxing `ts` with AVC? 🙄❓

**Comment by 44vince44** [comment]
yes Stax told me about an older ts format (with an avc stream) that did not work corrrectly with eac3to

**Comment by Dendraspis** [comment]
eac3to will always have issues with some audio tracks, especially eac3 😂 , especially if they have a delay set. So it is pure luck, that eac3to can handle this test file. If they would create it with an eac3 audio track and maybe with a delay, it could/would crash.

**Comment by JJKylee** [comment]
I agree with @Dendraspis.

This whole topic of demuxing `ts` and `m2ts` seems like more of a usage issue than something that can be resolved by default StaxRip preprocessor settings. 🤔

**Comment by Dendraspis** [comment]
But it seems we can now.  😁 

I refurbished the command line for ffmpeg, now it should be able to handle all TS and M2TS files.

**Comment by 44vince44** [comment]
@JJKylee the command currently used is
`-probesize 10M -i "%source_file%" -map 0 -c copy -ignore_unknown -y -hide_banner "%temp_file%.mkv"`

And this is something you almost did all right ?

Do you remember which file required to use that command instead of the `-vn -sn -c:a copy ` string ?

**Comment by JJKylee** [comment]
> Do you remember which file required to use that command instead of the `-vn -sn -c:a copy ` string ?

See [here](https://github.com/staxrip/staxrip/issues/599#issuecomment-800966506).

BTW, I just replaced `-sn`(no subtitles) with `-map 0`(all streams) in the command line. Without `-map 0`, ffmpeg outputs _only a single stream_ for each type (video, audio, subtitle, etc.) that's suitable for output container format.

**Comment by Dendraspis** [comment]
@JJKylee 
Is there a reason why we should re-mux TS and M2TS files instead of de-muxing them?

**Comment by JJKylee** [comment]
My guess is 'to get an `mkv` file that's workable on StaxRip'...?

Like you said, maybe we can demux video streams to elementary streams and work on them directly. But in this case timestamp information (along with resolution, etc.) is lost on elementary streams, so remuxing to another container may be problematic.

But that's my guess. Maybe there's a reason it's there. @stax76, do you remember why?

**Comment by 44vince44** [comment]
In my own experience, LONG time ago, basic `.ts` files from the internet did not load in staxrip, unless you renamed them to `.mpg`.

So Stax76 introduces the pre-process of remuxing to mkv and it worked.

Now, I notices that if I disable the pre-process remuxing, those same files load correctly...

**Comment by Dendraspis** [comment]
Ok, so we can get rid of it.
In my tests it's not even necessary to demux it into a file - StaxRip uses it like it uses stream inside MKV containers.

There can't be an current reason, when I can demux it on-the-fly without issues.  🤔 
It must be an old problem, that is gone meanwhile.
That being said:  Maybe it was the wrong ffmpeg command line, that I had to fix in order to work, that caused this *myth* ?

**Comment by 44vince44** [comment]
But I thing it's preferable to demux, so we have AUDIO WHEN WE PREVIEW !

**Comment by Dendraspis** [comment]
@44vince44 
Why there should be no audio ??  😕

**Comment by JJKylee** [comment]
> But it seems we can now. 😁
> 
> I refurbished the command line for ffmpeg, now it should be able to handle all TS and M2TS files.

OK. So what's your recipe, then? 🙄❓

**Comment by Dendraspis** [comment]
I set *ffmpeg: Demux* as default for ts and m2ts files.
With that setting I encoded 10+ TS and M2TS files - all without issue.

**Comment by 44vince44** [comment]
@Dendraspis when you preview your AVS script with mpv.net, (press F9 from code editor or from preview window), if audio is not present as a separate file, there will be no audio.
This is how Staxrip has always worked.

**Comment by JJKylee** [comment]
> I set _ffmpeg: Demux_ as default for ts and m2ts files.
> With that setting I encoded 10+ TS and M2TS files - all without issue.

You demuxed **_audios_** as well?

What about the samples on 4kmedia.org including `LG: OLED Art HDR` and `LG: New York HDR`?
Do they demux without problems including the audio tracks with your solution? 🙄

**Comment by Dendraspis** [comment]
@44vince44 
Yes, and why should there be no audio file when you tell the demuxer to demux it?
Using the OLED demo file (renamed to `Demo.ts`) with stock settings gives you a temp folder with these files, immediately after ffmpeg finished reading it:
![image](https://user-images.githubusercontent.com/50659978/112760531-91c17180-8ff7-11eb-8add-6b91de10f307.png)

Just for you I opened Preview and started mpv and (of course) it worked.  😉 

To clarify:
Inside StaxRip the TS file behaves like an MKV container ... for me.


> You demuxed **_audios_** as well?

Of course, because I used fresh settings, so the **und**defined audio track was demuxed.

**Comment by JJKylee** [comment]
But ffmpeg fails to demux/remux the problematic audio track in _2.2.0_.
If it's resolved in your fix, then it's a big progress. 👍

**Comment by Dendraspis** [comment]
Which problematic audio track ?
You mean `LG: New York HDR`  ?

**Comment by JJKylee** [comment]
No. `LG OLED Art HDR UHD 4K Demo.ts`. It fails in 2.2.0.

**Comment by Dendraspis** [comment]
@JJKylee 
Did you see my screenshots?  😉  😁

**Comment by JJKylee** [comment]
OK. I've also found a solution to the `LG OLED Art HDR UHD 4K Demo.ts` audio demuxing issue.

I just increased the `probesize` value from `10M` to `50M`, and it works.

@Dendraspis, if your solution is different than mine but you're sure it's universal, then go ahead.
Meanwhile, I'll settle for a _higher_ `probesize` value.

**Comment by Dendraspis** [comment]
@JJKylee 

Just for you:

```
General
Unique ID                      : 105289299693938264029823668067622006834 (0x4F35FB44442F299B7FE2102894C53032)
Complete name                  : A:\LG OLED Art HDR UHD 4K Demo.mkv
Format                         : Matroska
Format version                 : Version 4
File size                      : 16.0 MiB
Duration                       : 1 min 14 s
Overall bit rate               : 1 788 kb/s
Encoded date                   : UTC 2021-03-28 17:48:29
Writing application            : mkvmerge v55.0.0 ('Waiting For Space') 64-bit
Writing library                : libebml v1.4.2 + libmatroska v1.6.4

Video
ID                             : 1
Format                         : HEVC
Format/Info                    : High Efficiency Video Coding
Format profile                 : Main 10@L5.1@Main
HDR format                     : SMPTE ST 2086, HDR10 compatible
Codec ID                       : V_MPEGH/ISO/HEVC
Duration                       : 1 min 14 s
Bit rate                       : 1 402 kb/s
Width                          : 3 840 pixels
Height                         : 2 160 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 59.940 (60000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0 (Type 2)
Bit depth                      : 10 bits
Bits/(Pixel*Frame)             : 0.003
Stream size                    : 12.5 MiB (78%)
Writing library                : x265 3.5+9+14-6c69ed37d:[Windows][GCC 10.2.0][64 bit] 10bit
Encoding settings              : cpuid=1111039 / frame-threads=4 / numa-pools=24 / wpp / no-pmode / no-pme / no-psnr / no-ssim / log-level=2 / input-csp=1 / input-res=3840x2160 / interlace=0 / total-frames=4494 / level-idc=0 / high-tier=1 / uhd-bd=0 / ref=1 / no-allow-non-conformance / repeat-headers / annexb / aud / no-hrd / info / hash=0 / no-temporal-layers / open-gop / min-keyint=25 / keyint=250 / gop-lookahead=0 / bframes=3 / b-adapt=0 / b-pyramid / bframe-bias=0 / rc-lookahead=5 / lookahead-slices=8 / scenecut=0 / hist-scenecut=0 / radl=0 / no-splice / no-intra-refresh / ctu=32 / min-cu-size=16 / no-rect / no-amp / max-tu-size=32 / tu-inter-depth=1 / tu-intra-depth=1 / limit-tu=0 / rdoq-level=0 / dynamic-rd=0.00 / no-ssim-rd / no-signhide / no-tskip / nr-intra=0 / nr-inter=0 / no-constrained-intra / strong-intra-smoothing / max-merge=2 / limit-refs=0 / no-limit-modes / me=0 / subme=0 / merange=57 / temporal-mvp / no-frame-dup / no-hme / no-weightp / no-weightb / no-analyze-src-pics / no-deblock / no-sao / no-sao-non-deblock / rd=2 / selective-sao=0 / early-skip / rskip / fast-intra / no-tskip-fast / no-cu-lossless / no-b-intra / no-splitrd-skip / rdpenalty=0 / psy-rd=2.00 / psy-rdoq=0.00 / no-rd-refine / no-lossless / cbqpoffs=0 / crqpoffs=0 / rc=crf / crf=24.0 / qcomp=0.60 / qpstep=4 / stats-write=0 / stats-read=0 / ipratio=1.40 / pbratio=1.30 / aq-mode=1 / aq-strength=0.00 / cutree / zone-count=0 / no-strict-cbr / qg-size=32 / no-rc-grain / qpmax=69 / qpmin=0 / no-const-vbv / sar=0 / overscan=0 / videoformat=5 / range=0 / colorprim=9 / transfer=16 / colormatrix=9 / chromaloc=1 / chromaloc-top=2 / chromaloc-bottom=2 / display-window=0 / master-display=G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(12000000,500) / cll=0,0 / min-luma=0 / max-luma=1023 / log2-max-poc-lsb=8 / vui-timing-info / vui-hrd-info / slices=1 / no-opt-qp-pps / no-opt-ref-list-length-pps / no-multi-pass-opt-rps / scenecut-bias=0.05 / hist-threshold=0.03 / no-opt-cu-delta-qp / no-aq-motion / hdr10 / no-hdr10-opt / no-dhdr10-opt / no-idr-recovery-sei / analysis-reuse-level=0 / analysis-save-reuse-level=0 / analysis-load-reuse-level=0 / scale-factor=0 / refine-intra=0 / refine-inter=0 / refine-mv=1 / refine-ctu-distortion=0 / no-limit-sao / ctu-info=0 / no-lowpass-dct / refine-analysis-type=0 / copy-pic=1 / max-ausize-factor=1.0 / no-dynamic-refine / no-single-sei / no-hevc-aq / no-svt / no-field / qp-adaptation-range=1.00 / scenecut-aware-qp=0conformance-window-offsets / right=0 / bottom=0 / decoder-max-rate=0 / no-vbv-live-multi-pass
Default                        : Yes
Forced                         : No
Color range                    : Limited
Color primaries                : BT.2020
Transfer characteristics       : PQ
Matrix coefficients            : BT.2020 non-constant
Mastering display color primar : Display P3
Mastering display luminance    : min: 0.0500 cd/m2, max: 1200 cd/m2

Audio
ID                             : 2
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Codec ID                       : A_AAC-2
Duration                       : 1 min 14 s
Bit rate                       : 384 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 46.875 FPS (1024 SPF)
Compression mode               : Lossy
Stream size                    : 3.41 MiB (21%)
Language                       : English
Default                        : No
Forced                         : No
```

**Comment by JJKylee** [comment]
We were talking about the situation that `LG OLED Art HDR UHD 4K Demo.ts` couldn't be _demuxed_ in 2.2.0 _with the current command line_.

And yes, if we disable the ffmpeg _remux_ preprocessor, we can load it, but the audio itself is not extracted. We just do a job on the audio track muxed in the source `ts` file.

I suggest that we can fix it by increasing the `probesize` value to `50M` for both ffmpeg demuxer and ffmpeg remux preprocessor.

And you didn't tell us what your SOLUTION is.

**Comment by 44vince44** [comment]
@JJKylee he (@Dendraspis) made a solution where ffmpeg demuxes every single track and it works ! You'll check it by yourself in a few minutes... don't forget to restore to default the preprocessors...

**Comment by Dendraspis** [comment]
@44vince44 
Or now, if he would be online.  😉 

> And yes, if we disable the ffmpeg remux preprocessor, we can load it, but the audio itself is not extracted. 

Again: why it should not be demuxed?
Go online and test it by yourself.  😉 

> And you didn't tell us what your SOLUTION is.

Because there is no big solution. It works even with `-probesize 10M`.  
@44vince44 was also confused, but he confirmed that it works.

**Comment by 44vince44** [comment]
I'm still doing tests... till now all is ok...

**Comment by JJKylee** [comment]
Demux every single track...? That means we batch run the demux process stream by stream. Hahaha... 😅
That makes sense.

OK. Let me give it a try.

**Comment by 44vince44** [comment]
yes but I made a file that creates a crash, and could make your point about probesize: a ts file with
- video
- 
- Audio DTS HD <- this is important, this should be the reason of crash...
- srt subtitles

**Comment by JJKylee** [comment]
Oh, BTW, `LG OLED Art HDR UHD 4K Demo.ts` was able to be remuxed to mkv with `ffmpeg remux to mkv` preprocessor by adding `-dn`(no data streams) option in the command line. On second try, I've found that `-probesize 10M` also works nicely with it as long as `-dn` is included.

**Comment by 44vince44** [comment]
Wait both of you that the SUPER FAILING file is online....

**Comment by JJKylee** [comment]
> and it fails to demux the dtshd stream....

Can you increase the `probesize` value to like `50M` and give it a try again in CMD?

**Comment by 44vince44** [comment]
yes I did and i added analyzeduration 100M also, the error changed.
I sent you a link to the file on discord

**Comment by stax76** [comment]
The first ten years of staxrip I was a DVB user, I had developed a full-blown DVB app like ProgDVB using C++/CLR including decryption support with special plugins..., it was called KeyDVB. Users had sent me all kind of sample TS DVB recording they had issues with, unfortunately I lost this sample collection, ffms2 or L-Smash never could handle those samples, async audio all the time. Remuxing to mkv with ffmpeg was the most successful method. I hate to say it, but DG source filters could handle it well, TS is in my experience the only good reason to use DG tools, DG tools are overrated like madshi tool. I don't know if people still record DVB.

**Comment by JJKylee** [comment]
I can see that ffmpeg _remux to mkv_ failed because

```
[matroska @ 000002247e6a00c0] Only audio, video, and subtitles are supported for Matroska.
```

That's why I came up with `-dn`(no data streams) along with `-map 0`(all streams). Combined, they map audio video, and subtitle streams only to the output `mkv` file.

And for a big size file, we need to increase `-probesize` to a higher value like `50M`.

So with @44vince44's problematic source, `DTS HD Living World Of Audio dtshd sample with subs_pgs.ts`, I was able to remux it to mkv with ffmpeg with the following command line:

```
-probesize 50M -i "%source_file%" -map 0 -dn -c copy -ignore_unknown -y -hide_banner "%temp_file%.mkv"
```

**Comment by 44vince44** [comment]
@JJKylee great find ! 
@Dendraspis thos could be the way to go...

@stax76 we could maybe use some additional info: ts files outputted by DVB devices are always AVC ? or could they have another codec ?

**Comment by JJKylee** [comment]
For ffmpeg demux, ffmpeg can't demux to _elementary_ streams unlike `mkvextract`.

With @44vince44's sample, `DTS HD Living World Of Audio dtshd sample with subs_pgs.ts`, the demux issue is resolved if the extension `dtshd` is changed to `mka` like this:

```
[...]\ffmpeg.exe -y -hide_banner -probesize 10M -i "[...]\DTS HD Living World Of Audio dtshd sample with subs_pgs.ts" -vn -sn -c:a copy "[...]\DTS HD Living World Of Audio dtshd sample with subs_pgs ID1 English.mka"
```

**Comment by 44vince44** [comment]
So it would create a DTSHD wrapped in an mka

**Comment by JJKylee** [comment]
Let me correct my above reply.

FFmpeg cannot demux a `dtshd` file as is _from `ts` input_. But once the `ts` file is remuxed to `mkv`, then ffmpeg can demux `dtshd` file from the `mkv` file.

It's weird, but I just confirmed it. 😂

**Comment by Dendraspis** [comment]
Okay, this is even easier. Instead of demuxing into an mka container, you can use simply use `filename.dts` instead of `filename.dtshd`.

**Comment by 44vince44** [comment]
lol, and does it keep the dtshd structure or extract the core ?

**Comment by Dendraspis** [comment]
![image](https://user-images.githubusercontent.com/50659978/112766551-99424400-9012-11eb-858c-ab6035706bab.png)

**Comment by 44vince44** [comment]
which rises the question: if the file is called *.dts, if the user wants to extract the core, will staxrip be able to do it ?
Because Staxrip is programmed to know a dtshd file from its extension : dtshd or mka

**Comment by JJKylee** [comment]
It's possible but we need to change the filename to something like `*_new.dts`.
But this may raise confusion: `dtshd` and `dts` having the same extension. 😅
I'd rather go with `mka` and make `dtshd`/`dts` from it, as in the above screenshot.

**Comment by Dendraspis** [comment]
Keep cool, solution is already implemented.
The next release is coming soon ...

**Comment by 44vince44** [comment]
@JJKylee for the record, I was able to create a dtshd-in-mka file with this command, from the original ts file (not remuxed):

`ffmpeg.exe -y -hide_banner -probesize 10M -i "DTS HD Living World Of Audio dtshd sample with subs_pgs.ts" -dn -vn -sn -c:a copy "ID1 English.mka"`

**Comment by JJKylee** [comment]
Yeah. `ts` ⇒ `mka(dtshd inside)` or `mkv` ⇒ `dtshd` is possible with ffmpeg.
`ts` ⇒ `dts(dtshd inside)` is also possible. It is **`ts` ⇒ `dtshd`** that is NOT possible with ffmpeg.

And `mka(dtshd inside)` ⇒ `dts`(core) is also possible with ffmpeg.

It seems that `mka(dtshd inside)` ⇒ `dtshd` by stream copy is NOT possible with ffmpeg.

So basically ffmpeg doesn't seem to like outputting a `dtshd` file. 🤔

**Comment by JJKylee** [comment]
Sorry. I was wrong about this: "`mkv` ⇒ `dtshd` is possible with `ffmpeg`."

According to ffmpeg documentation, _`ffmpeg` does not support `dtshd` raw format itself_.
Only `dts` raw format is possible.

The `mkv` ⇒ `dtshd` process was possible because of `mkvextract` implicitly employed by StaxRip for an extra audio extraction job. 😅

**Comment by Dendraspis** [comment]
@JJKylee 
No, you were not wrong.  It is possible when setting the format via `-f`.  😉 

v2.3.0 is out now ...

**Comment by JJKylee** [comment]
> It is possible when setting the format via `-f`. 😉

Really? Good to know. 😲😊
